rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - rbx-2.0
  - ree
  # - jruby
  - ruby-head
# env:
#   - SPHINX_BIN=/usr/local/sphinx-0.9.9/bin
#   - SPHINX_BIN=/usr/local/sphinx-1.10/bin
#   - SPHINX_BIN=/usr/local/sphinx-2.0.1/bin
